server:
  port: 80
      
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/goodkin?serverTimezone=Asia/Seoul
    username: root
    password: 1111

  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      maxFileSize: 500MB
      maxRequestSize: 500MB
        
mybatis:
  type-aliases-package: com.goodkin.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: OFF
      sqlonly: OFF
      sqltiming: INFO
      connection : OFF

cloud:
  aws:  
    credentials:
      access-key: AKIA3LJCETV4ED72XSXX
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: goodkin-bucket
      url: https://goodkin-bucket.s3.ap-northeast-2.amazonaws.com/
    stack:
      auto: false