server:
  port: 80
      
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/joeunfc2022?serverTimezone=Asia/Seoul&allowMultiQueries=true
    # driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    # url: jdbc:log4jdbc:mariadb://goodchicken.co.kr:3306/joeunfc2022?serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: joeunfc2022
    password: Goodchicken2022!
    
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      maxFileSize: 500MB
      maxRequestSize: 500MB
        
mybatis:
  type-aliases-package: com.goodkin.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: OFF
      sqlonly: OFF
      sqltiming: INFO
      connection : OFF

# CDN
cdn:
  ip: iup.cdn1.cafe24.com
  port: 21
  username: joeunfc2022
  password: Goodchicken2022!

#naver
naver:
  client:
    id: sg6n0oldss
    secret: CQM5yLrbgemhoWeQ2anzpmeo7Hke9AuGsuurvXn1